### ISSUE TITLE
ReadImage Fails

### ISSUE THREAD

**Issue by jimpipe** [gpilab/core-nodes#3] opened 2016-01-07 23:24 UTC
With the latest GPI, when instantiating the ReadImage node it fails immediately, with feedback:

Thu Jan  7 16:21:17 2016 - gpi.functor:369 - ERROR - PROCESS: 'ReadImage':'' compute() failed.
Traceback (most recent call last):
  File "/Applications/GPI.app/Contents/Resources/miniconda/lib/python3.5/site-packages/gpi/functor.py", line 367, in run
    self._proxy.append(['retcode', self._func()])
  File "/Applications/GPI.app/Contents/Resources/miniconda/lib/python3.5/site-packages/gpi/node-libs/core/fileIO/GPI/ReadImage_GPI.py", line 85, in compute
    from PIL import Image
ImportError: No module named 'PIL'

Thu Jan  7 16:21:17 2016 - gpi.node:601 - ERROR - ReadImage: compute() failed.

**Comment by aganders3** [comment] 2016-02-25 20:30
This should be fixed in the latest build. You can get the fix through the GPI self-updater by launching GPI and selecting "GPI -> Check For Updates..." from the menu bar.

_What happened:_
`pillow` (a drop-in replacement for `pil`) was not included in the list of dependencies on the 1.0.0 version of the `gpi-core-nodes` package on Anaconda Cloud. The new version (1.0.1) was uploaded, but only in the `rc` channel, while the GPI self-updater looks at the `main` channel. I added the new(er) builds to the `main` channel and now everything works as intended.

**Closed as completed by aganders3** 2016-02-25 20:30 UTC
